name: aws_chime_example
description: Demonstrates how to use the aws_chime plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  aws_chime:
    path: ../
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  flutter_dotenv: ^5.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
