platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'AmazonChimeSDK-Bitcode', '~> 0.22.4'

end
